baseURL = 'https://example.org/'
DefaultContentLanguage = "en"
languageCode = 'en-us'
title = 'The Matchless Wisdom Blog'
theme = "github.com/halogenica/beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[[module.imports]]
  path = "github.com/halogenica/beautifulhugo"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Explore the boundless wisdom of ancient Vedic teachings at Matchless Wisdom. Our blog offers insightful articles on Vedic philosophy and spiritual well-being."
  mainSections = ["post","posts"]
  logo = "img/matchless-wisdom-logo-bg.png"
  favicon = "img/matchless-wisdom-logo-bg.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  disqusShortname = "matchlesswisdom-com"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Matchless Wisdom"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "about/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "contact/"
    weight = 5